### ISSUE TITLE
no update for montrey?

### ISSUE THREAD

**Issue by irfanhutomo2** [theisyraff/HacOS-Vivobook-A409JA#1]

**Comment by theisyraff** [comment]
I'm so sorry, I haven't updated my GitHub for a while. I already updated my Machine with macOS Monterey, and currently on OpenCore 0.7.7. Hang on a minute, and I'll upload a new update for OpenCore.

**Comment by mrwiwi** [comment]
That would be awesome, I can't get past a KP CR2 fault for 2 days now.... thanks a lot in advance !

**Comment by mrwiwi** [comment]
*and if you could detail your bios version & settings please too, i'm really stuck on that early KP, it's my 5th hackintosh but I can't make sense of that one :( tried everything (included restarting from scratch). Thanks !

**Comment by theisyraff** [comment]
I have released a new Opencore update for Opencore 0.7.7 for Vivobook A409J. Y'all can have a try. This is tested with my machine and it has worked perfectly for the past 3 months. Make sure to key in your SMBIOS and Serial Numbers before that.

**Comment by mrwiwi** [comment]
Still KP... what's your bios version please ? I'm on 310, 64mb GPU RAM, secure boot disabled.

**Comment by mrwiwi** [comment]
Working thanks a lot !

**Comment by theisyraff** [comment]
About the BIOS version, yeah I used the current 310 version. 64mb of GPU VRAM, with secure boot disabled.
