### ISSUE TITLE
Were you able to get HDMI out working 

### ISSUE THREAD

**Issue by Bhavinjain260** [theisyraff/HacOS-Vivobook-A409JA#3]
I got similar lap vivo book x515ja i3 10 gen 
We're you able to get it working?

**Comment by theisyraff** [comment]
I haven't tested it out. Have you tested it?

**Comment by Bhavinjain260** [comment]
No 

No output

**Comment by theisyraff** [comment]
https://www.icloud.com/iclouddrive/010ZOljCvCwudamjCcsRsSrlg#EFI_2

try this
If it works, I'll release a new file.

**Comment by Bhavinjain260** [comment]
Sure

**Comment by Bhavinjain260** [comment]
Can use using different platform 

Share from this 


https://ufile.io

**Comment by theisyraff** [comment]
https://ufile.io/ijzx32rv

**Comment by Bhavinjain260** [comment]
not working 

for Icelake Based system HDMI is not working
